# Generated by Django 5.2.5 on 2025-08-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compendium", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monster",
            old_name="link",
            new_name="url",
        ),
        migrations.RemoveField(
            model_name="monster",
            name="source",
        ),
    ]
