# Generated by Django 5.2.5 on 2025-08-21 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(max_length=200)),
                ("player_name", models.CharField(max_length=100)),
                ("character_race", models.CharField(max_length=200)),
                (
                    "character_subrace",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("character_class", models.CharField(max_length=200)),
                (
                    "character_subclass",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("ac", models.IntegerField(blank=True, null=True)),
                ("hp", models.IntegerField(blank=True, null=True)),
                ("info", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
