# Generated by Django 5.2.5 on 2025-08-25 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0003_alter_monsterencounterdata_encounter_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encounters",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
