# Generated by Django 5.2.5 on 2025-08-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("cr", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=100)),
                ("ac", models.IntegerField()),
                ("hp", models.IntegerField()),
                ("source", models.CharField(max_length=255)),
            ],
        ),
    ]
